# Etapa 1: Construção do binário
FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/api ./cmd/api/main.go
RUN go build -o /app/bin/schedule ./cmd/schedule/main.go

# Etapa 2: Criação da imagem final
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/bin/api /app/bin/api
COPY --from=builder /app/bin/schedule /app/bin/schedule

# Variáveis de ambiente que a aplicação precisa em tempo de execução
ENV DB_HOST=${DB_HOST}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}
ENV DB_PORT=${DB_PORT}

ENV APP_DEBUG=${APP_DEBUG}
ENV APP_ENV=${APP_ENV}

ENV API_PORT=${API_PORT}

ENV CLOCK_LOCATION=${CLOCK_LOCATION}

ENV INVOICE_EXPIRATION_DAYS=${INVOICE_EXPIRATION_DAYS}
ENV INVOICE_RANDOM_INVOICES_NUMBER_MIN=${INVOICE_RANDOM_INVOICES_NUMBER_MIN}
ENV INVOICE_RANDOM_INVOICES_NUMBER_MAX=${INVOICE_RANDOM_INVOICES_NUMBER_MAX}

ENV BANK_ACCOUNT_NAME=${BANK_ACCOUNT_NAME}
ENV BANK_ACCOUNT_TAX_ID=${BANK_ACCOUNT_TAX_ID}
ENV BANK_ACCOUNT_BANK_CODE=${BANK_ACCOUNT_BANK_CODE}
ENV BANK_ACCOUNT_BRANCH_CODE=${BANK_ACCOUNT_BRANCH_CODE}
ENV BANK_ACCOUNT_ACCOUNT_NUMBER=${BANK_ACCOUNT_ACCOUNT_NUMBER}
ENV BANK_ACCOUNT_ACCOUNT_TYPE=${BANK_ACCOUNT_ACCOUNT_TYPE}

ENV SCHEDULER_ENABLED=${SCHEDULER_ENABLED}
ENV INVOICE_CREATE_SCHEDULED_TIME=${INVOICE_CREATE_SCHEDULED_TIME}

ENV STARKBANK_PROJECT_ID=${STARKBANK_PROJECT_ID}
ENV STARKBANK_ENVIRONMENT=${STARKBANK_ENVIRONMENT}
ENV STARKBANK_PRIVATE_KEY=${STARKBANK_PRIVATE_KEY}
ENV STARKBANK_PUBLIC_KEY=${STARKBANK_PUBLIC_KEY}

# Exponha a porta que a aplicação irá utilizar
EXPOSE ${API_PORT}

# Defina o comando de entrada para o container
CMD ["/app/bin/api"]
