// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/interfaces/bank_gateway.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dtos "joaosalless/challenge-starkbank/src/dtos"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBankGateway is a mock of BankGateway interface.
type MockBankGateway struct {
	ctrl     *gomock.Controller
	recorder *MockBankGatewayMockRecorder
}

// MockBankGatewayMockRecorder is the mock recorder for MockBankGateway.
type MockBankGatewayMockRecorder struct {
	mock *MockBankGateway
}

// NewMockBankGateway creates a new mock instance.
func NewMockBankGateway(ctrl *gomock.Controller) *MockBankGateway {
	mock := &MockBankGateway{ctrl: ctrl}
	mock.recorder = &MockBankGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankGateway) EXPECT() *MockBankGatewayMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockBankGateway) CreateInvoice(ctx context.Context, input dtos.CreateInvoiceInput) (dtos.CreateInvoiceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, input)
	ret0, _ := ret[0].(dtos.CreateInvoiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockBankGatewayMockRecorder) CreateInvoice(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockBankGateway)(nil).CreateInvoice), ctx, input)
}

// CreateTransfer mocks base method.
func (m *MockBankGateway) CreateTransfer(ctx context.Context, input dtos.CreateTransferInput) (dtos.CreateTransferOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, input)
	ret0, _ := ret[0].(dtos.CreateTransferOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockBankGatewayMockRecorder) CreateTransfer(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockBankGateway)(nil).CreateTransfer), ctx, input)
}
